# Install script for directory: C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/aws-cpp-sdk-all")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/Debug/aws-cpp-sdk-ssm.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/DebugOpt/aws-cpp-sdk-ssm.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/Release/aws-cpp-sdk-ssm.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/RelWithDebInfo/aws-cpp-sdk-ssm.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/MinSizeRel/aws-cpp-sdk-ssm.lib")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/Debug/aws-cpp-sdk-ssm.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/DebugOpt/aws-cpp-sdk-ssm.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/Release/aws-cpp-sdk-ssm.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/RelWithDebInfo/aws-cpp-sdk-ssm.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/MinSizeRel/aws-cpp-sdk-ssm.dll")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/pkgconfig" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm.pc")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/aws/ssm" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/SSMClient.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/SSMEndpoint.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/SSMErrorMarshaller.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/SSMErrors.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/SSMRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/SSM_EXPORTS.h"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/aws/ssm/model" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AccountSharingInfo.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/Activation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AddTagsToResourceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AddTagsToResourceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/Association.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationComplianceSeverity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationExecution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationExecutionFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationExecutionFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationExecutionTarget.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationExecutionTargetsFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationExecutionTargetsFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationFilterOperatorType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationOverview.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationStatusName.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationSyncCompliance.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AssociationVersionInfo.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AttachmentContent.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AttachmentHashType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AttachmentInformation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AttachmentsSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AttachmentsSourceKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AutomationExecution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AutomationExecutionFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AutomationExecutionFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AutomationExecutionMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AutomationExecutionStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/AutomationType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CalendarState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CancelCommandRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CancelCommandResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CancelMaintenanceWindowExecutionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CancelMaintenanceWindowExecutionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CloudWatchOutputConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/Command.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CommandFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CommandFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CommandInvocation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CommandInvocationStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CommandPlugin.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CommandPluginStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CommandStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ComplianceExecutionSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ComplianceItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ComplianceItemEntry.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ComplianceQueryOperatorType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ComplianceSeverity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ComplianceStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ComplianceStringFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ComplianceSummaryItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ComplianceUploadType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CompliantSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ConnectionStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateActivationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateActivationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateAssociationBatchRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateAssociationBatchRequestEntry.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateAssociationBatchResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateAssociationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateAssociationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateDocumentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateDocumentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateMaintenanceWindowRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateMaintenanceWindowResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateOpsItemRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateOpsItemResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreatePatchBaselineRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreatePatchBaselineResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateResourceDataSyncRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/CreateResourceDataSyncResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteActivationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteActivationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteAssociationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteAssociationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteDocumentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteDocumentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteInventoryRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteInventoryResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteMaintenanceWindowRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteMaintenanceWindowResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteParameterRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteParameterResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteParametersRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteParametersResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeletePatchBaselineRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeletePatchBaselineResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteResourceDataSyncRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeleteResourceDataSyncResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeregisterManagedInstanceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeregisterManagedInstanceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeregisterPatchBaselineForPatchGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeregisterPatchBaselineForPatchGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeregisterTargetFromMaintenanceWindowRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeregisterTargetFromMaintenanceWindowResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeregisterTaskFromMaintenanceWindowRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DeregisterTaskFromMaintenanceWindowResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeActivationsFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeActivationsFilterKeys.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeActivationsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeActivationsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAssociationExecutionTargetsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAssociationExecutionTargetsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAssociationExecutionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAssociationExecutionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAssociationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAssociationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAutomationExecutionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAutomationExecutionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAutomationStepExecutionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAutomationStepExecutionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAvailablePatchesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeAvailablePatchesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeDocumentPermissionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeDocumentPermissionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeDocumentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeDocumentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeEffectiveInstanceAssociationsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeEffectiveInstanceAssociationsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeEffectivePatchesForPatchBaselineRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeEffectivePatchesForPatchBaselineResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInstanceAssociationsStatusRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInstanceAssociationsStatusResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInstanceInformationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInstanceInformationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInstancePatchStatesForPatchGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInstancePatchStatesForPatchGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInstancePatchStatesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInstancePatchStatesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInstancePatchesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInstancePatchesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInventoryDeletionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeInventoryDeletionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowExecutionTaskInvocationsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowExecutionTaskInvocationsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowExecutionTasksRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowExecutionTasksResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowExecutionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowExecutionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowScheduleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowScheduleResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowTargetsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowTargetsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowTasksRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowTasksResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowsForTargetRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowsForTargetResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeMaintenanceWindowsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeOpsItemsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeOpsItemsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeParametersRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeParametersResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribePatchBaselinesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribePatchBaselinesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribePatchGroupStateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribePatchGroupStateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribePatchGroupsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribePatchGroupsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribePatchPropertiesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribePatchPropertiesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeSessionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DescribeSessionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentDefaultVersionDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentFormat.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentHashType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentIdentifier.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentKeyValuesFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentParameter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentParameterType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentPermissionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentRequires.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/DocumentVersionInfo.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/EffectivePatch.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ExecutionMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/FailedCreateAssociation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/FailureDetails.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/Fault.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetAutomationExecutionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetAutomationExecutionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetCalendarStateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetCalendarStateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetCommandInvocationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetCommandInvocationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetConnectionStatusRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetConnectionStatusResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetDefaultPatchBaselineRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetDefaultPatchBaselineResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetDeployablePatchSnapshotForInstanceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetDeployablePatchSnapshotForInstanceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetDocumentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetDocumentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetInventoryRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetInventoryResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetInventorySchemaRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetInventorySchemaResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetMaintenanceWindowExecutionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetMaintenanceWindowExecutionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetMaintenanceWindowExecutionTaskInvocationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetMaintenanceWindowExecutionTaskInvocationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetMaintenanceWindowExecutionTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetMaintenanceWindowExecutionTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetMaintenanceWindowRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetMaintenanceWindowResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetMaintenanceWindowTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetMaintenanceWindowTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetOpsItemRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetOpsItemResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetOpsSummaryRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetOpsSummaryResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetParameterHistoryRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetParameterHistoryResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetParameterRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetParameterResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetParametersByPathRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetParametersByPathResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetParametersRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetParametersResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetPatchBaselineForPatchGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetPatchBaselineForPatchGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetPatchBaselineRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetPatchBaselineResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetServiceSettingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/GetServiceSettingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstanceAggregatedAssociationOverview.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstanceAssociation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstanceAssociationOutputLocation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstanceAssociationOutputUrl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstanceAssociationStatusInfo.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstanceInformation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstanceInformationFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstanceInformationFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstanceInformationStringFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstancePatchState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstancePatchStateFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InstancePatchStateOperatorType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InvalidItemContentException.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryAggregator.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryAttributeDataType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryDeletionStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryDeletionStatusItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryDeletionSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryDeletionSummaryItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryGroup.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryItemAttribute.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryItemSchema.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryQueryOperatorType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryResultEntity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventoryResultItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/InventorySchemaDeleteOption.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ItemContentMismatchException.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ItemSizeLimitExceededException.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/LabelParameterVersionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/LabelParameterVersionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/LastResourceDataSyncStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListAssociationVersionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListAssociationVersionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListAssociationsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListAssociationsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListCommandInvocationsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListCommandInvocationsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListCommandsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListCommandsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListComplianceItemsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListComplianceItemsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListComplianceSummariesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListComplianceSummariesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListDocumentVersionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListDocumentVersionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListDocumentsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListDocumentsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListInventoryEntriesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListInventoryEntriesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListResourceComplianceSummariesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListResourceComplianceSummariesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListResourceDataSyncRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListResourceDataSyncResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListTagsForResourceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ListTagsForResourceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/LoggingInfo.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowAutomationParameters.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowExecution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowExecutionStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowExecutionTaskIdentity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowExecutionTaskInvocationIdentity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowIdentity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowIdentityForTarget.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowLambdaParameters.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowResourceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowRunCommandParameters.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowStepFunctionsParameters.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowTarget.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowTask.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowTaskInvocationParameters.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowTaskParameterValueExpression.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/MaintenanceWindowTaskType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ModifyDocumentPermissionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ModifyDocumentPermissionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/NonCompliantSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/NotificationConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/NotificationEvent.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/NotificationType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OperatingSystem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsAggregator.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsEntity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsEntityItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsFilterOperatorType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItemAlreadyExistsException.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItemDataType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItemDataValue.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItemFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItemFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItemFilterOperator.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItemInvalidParameterException.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItemLimitExceededException.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItemNotification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItemStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsItemSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OpsResultAttribute.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/OutputSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/Parameter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ParameterHistory.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ParameterInlinePolicy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ParameterMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ParameterStringFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ParameterTier.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ParameterType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ParametersFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ParametersFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/Patch.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchBaselineIdentity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchComplianceData.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchComplianceDataState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchComplianceLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchDeploymentStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchFilterGroup.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchGroupPatchBaselineMapping.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchOperationType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchOrchestratorFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchProperty.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchRule.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchRuleGroup.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchSet.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PatchStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PingStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PlatformType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ProgressCounters.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PutComplianceItemsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PutComplianceItemsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PutInventoryRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PutInventoryResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PutParameterRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/PutParameterResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RebootOption.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RegisterDefaultPatchBaselineRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RegisterDefaultPatchBaselineResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RegisterPatchBaselineForPatchGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RegisterPatchBaselineForPatchGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RegisterTargetWithMaintenanceWindowRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RegisterTargetWithMaintenanceWindowResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RegisterTaskWithMaintenanceWindowRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RegisterTaskWithMaintenanceWindowResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RelatedOpsItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RemoveTagsFromResourceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/RemoveTagsFromResourceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResetServiceSettingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResetServiceSettingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResolvedTargets.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceComplianceSummaryItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceDataSyncAlreadyExistsException.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceDataSyncAwsOrganizationsSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceDataSyncDestinationDataSharing.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceDataSyncItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceDataSyncNotFoundException.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceDataSyncOrganizationalUnit.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceDataSyncS3Destination.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceDataSyncS3Format.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceDataSyncSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceDataSyncSourceWithState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResourceTypeForTagging.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResultAttribute.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResumeSessionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ResumeSessionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/S3OutputLocation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/S3OutputUrl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ScheduledWindowExecution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/SendAutomationSignalRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/SendAutomationSignalResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/SendCommandRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/SendCommandResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/ServiceSetting.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/Session.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/SessionFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/SessionFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/SessionManagerOutputUrl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/SessionState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/SessionStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/SeveritySummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/SignalType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StartAssociationsOnceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StartAssociationsOnceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StartAutomationExecutionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StartAutomationExecutionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StartSessionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StartSessionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StepExecution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StepExecutionFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StepExecutionFilterKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StopAutomationExecutionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StopAutomationExecutionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/StopType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/Tag.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/Target.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/TargetLocation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/TerminateSessionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/TerminateSessionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UnsupportedInventoryItemContextException.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateAssociationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateAssociationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateAssociationStatusRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateAssociationStatusResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateDocumentDefaultVersionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateDocumentDefaultVersionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateDocumentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateDocumentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateMaintenanceWindowRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateMaintenanceWindowResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateMaintenanceWindowTargetRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateMaintenanceWindowTargetResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateMaintenanceWindowTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateMaintenanceWindowTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateManagedInstanceRoleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateManagedInstanceRoleResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateOpsItemRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateOpsItemResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdatePatchBaselineRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdatePatchBaselineResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateResourceDataSyncRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateResourceDataSyncResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateServiceSettingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/include/aws/ssm/model/UpdateServiceSettingResult.h"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-targets.cmake")
    file(DIFFERENT EXPORT_FILE_CHANGED FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-targets.cmake"
         "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-targets.cmake")
    if(EXPORT_FILE_CHANGED)
      file(GLOB OLD_CONFIG_FILES "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-targets-*.cmake")
      if(OLD_CONFIG_FILES)
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-targets.cmake\" will be replaced.  Removing files [${OLD_CONFIG_FILES}].")
        file(REMOVE ${OLD_CONFIG_FILES})
      endif()
    endif()
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-ssm" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-targets.cmake")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-ssm" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-targets-debug.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-ssm" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-targets-debugopt.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-ssm" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-targets-minsizerel.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-ssm" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-targets-relwithdebinfo.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-ssm" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-targets-release.cmake")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xDevelx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-ssm" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-config.cmake"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/aws-cpp-sdk-ssm-config-version.cmake"
    )
endif()

