// Unity Build generated by CMake
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/source/MarketplaceCommerceAnalyticsClient.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/source/MarketplaceCommerceAnalyticsEndpoint.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/source/MarketplaceCommerceAnalyticsErrorMarshaller.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/source/MarketplaceCommerceAnalyticsErrors.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/source/model/DataSetType.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/source/model/GenerateDataSetRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/source/model/GenerateDataSetResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/source/model/StartSupportDataExportRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/source/model/StartSupportDataExportResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/source/model/SupportDataSetType.cpp>
