# Install script for directory: C:/Users/isaac/Projects/aws-sdk-cpp

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/aws-cpp-sdk-all")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/AWSSDK" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/AWSSDK/AWSSDKConfigVersion.cmake")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/AWSSDK" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/AWSSDK/platformDeps.cmake")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/AWSSDK" TYPE DIRECTORY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/cmake/")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include" TYPE DIRECTORY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/.deps/install/include/")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib" TYPE DIRECTORY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/.deps/install/lib/")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE DIRECTORY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/.deps/install/bin/")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-AWSMigrationHub/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-accessanalyzer/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-acm/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-acm-pca/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-alexaforbusiness/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-amplify/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigateway/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigatewaymanagementapi/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigatewayv2/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-appconfig/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-application-autoscaling/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-application-insights/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-appmesh/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-appstream/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-appsync/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-athena/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-autoscaling/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-autoscaling-plans/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-backup/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-batch/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-braket/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-budgets/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ce/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-chime/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cloud9/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-clouddirectory/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cloudformation/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cloudfront/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cloudhsm/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cloudhsmv2/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cloudsearch/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cloudsearchdomain/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cloudtrail/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-codeartifact/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-codebuild/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-codecommit/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-codedeploy/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-codeguru-reviewer/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-codeguruprofiler/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-codepipeline/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-codestar/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-codestar-connections/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-codestar-notifications/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cognito-identity/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cognito-idp/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cognito-sync/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-comprehend/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-comprehendmedical/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-compute-optimizer/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-config/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-connect/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-connectparticipant/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cur/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-dataexchange/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-datapipeline/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-datasync/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-dax/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-detective/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-devicefarm/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-directconnect/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-discovery/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-dlm/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-dms/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-docdb/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ds/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-dynamodb/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-dynamodbstreams/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ebs/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ec2/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ec2-instance-connect/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ecr/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ecs/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-eks/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-elastic-inference/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-elasticache/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-elasticbeanstalk/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-elasticfilesystem/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-elasticloadbalancing/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-elasticloadbalancingv2/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-elasticmapreduce/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-elastictranscoder/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-email/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplace-entitlement/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-es/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-eventbridge/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-events/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-firehose/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-fms/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-forecast/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-forecastquery/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-frauddetector/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-fsx/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-gamelift/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-glacier/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-globalaccelerator/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-glue/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-greengrass/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-groundstation/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-guardduty/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-health/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-honeycode/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iam/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-identitystore/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-imagebuilder/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-importexport/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-inspector/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-data/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot1click-devices/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot1click-projects/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iotanalytics/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iotevents/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iotevents-data/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iotsecuretunneling/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iotsitewise/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iotthingsgraph/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ivs/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kafka/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kendra/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-archived-media/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-media/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-signaling/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesisanalytics/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesisanalyticsv2/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesisvideo/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kms/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-lakeformation/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-lambda/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-lex-models/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-license-manager/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-lightsail/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-logs/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-machinelearning/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-macie/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-macie2/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-managedblockchain/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplace-catalog/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplacecommerceanalytics/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconnect/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediapackage/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediapackage-vod/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediastore/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediastore-data/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediatailor/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-migrationhub-config/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mobile/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mobileanalytics/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-monitoring/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mq/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mturk-requester/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-neptune/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-networkmanager/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-opsworks/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-opsworkscm/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-organizations/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-outposts/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-personalize/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-personalize-events/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-personalize-runtime/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-pi/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-pinpoint/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-pinpoint-email/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-polly/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-pricing/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-qldb/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-qldb-session/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-quicksight/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ram/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-rds/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-rds-data/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-redshift/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-rekognition/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-resource-groups/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-resourcegroupstaggingapi/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-robomaker/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-route53/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-route53domains/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-route53resolver/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-lex/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker-runtime/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-s3/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-s3control/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker-a2i-runtime/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-savingsplans/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-schemas/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sdb/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-secretsmanager/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-securityhub/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-serverlessrepo/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-service-quotas/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-servicecatalog/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-servicediscovery/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sesv2/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-shield/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-signer/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sms/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sms-voice/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-snowball/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sns/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sqs/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ssm/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sso/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sso-oidc/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-states/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-storagegateway/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sts/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-support/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-swf/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-synthetics/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-textract/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-transcribe/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-transcribestreaming/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-awstransfer/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-translate/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-waf/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-waf-regional/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-wafv2/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-workdocs/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-worklink/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-workmail/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-workmailmessageflow/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-workspaces/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-xray/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-core/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-access-management/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-identity-management/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-queues/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-transfer/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-s3-encryption/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-text-to-speech/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/testing-resources/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-cognitoidentity-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-dynamodb-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-ec2-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-elasticfilesystem-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-lambda-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-logs-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediastore-data-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-redshift-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-s3-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-s3control-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sqs-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-transcribestreaming-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-core-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-identity-management-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-transfer-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-s3-encryption-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-s3-encryption-integration-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-text-to-speech-tests/cmake_install.cmake")
  include("C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-polly-sample/cmake_install.cmake")

endif()

if(CMAKE_INSTALL_COMPONENT)
  set(CMAKE_INSTALL_MANIFEST "install_manifest_${CMAKE_INSTALL_COMPONENT}.txt")
else()
  set(CMAKE_INSTALL_MANIFEST "install_manifest.txt")
endif()

string(REPLACE ";" "\n" CMAKE_INSTALL_MANIFEST_CONTENT
       "${CMAKE_INSTALL_MANIFEST_FILES}")
file(WRITE "C:/Users/isaac/Projects/aws-sdk-cpp/${CMAKE_INSTALL_MANIFEST}"
     "${CMAKE_INSTALL_MANIFEST_CONTENT}")
