// Unity Build generated by CMake
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigatewaymanagementapi/source/ApiGatewayManagementApiClient.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigatewaymanagementapi/source/ApiGatewayManagementApiEndpoint.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigatewaymanagementapi/source/ApiGatewayManagementApiErrorMarshaller.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigatewaymanagementapi/source/ApiGatewayManagementApiErrors.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigatewaymanagementapi/source/model/DeleteConnectionRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigatewaymanagementapi/source/model/GetConnectionRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigatewaymanagementapi/source/model/GetConnectionResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigatewaymanagementapi/source/model/Identity.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-apigatewaymanagementapi/source/model/PostToConnectionRequest.cpp>
