// Unity Build generated by CMake
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-signaling/source/KinesisVideoSignalingChannelsClient.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-signaling/source/KinesisVideoSignalingChannelsEndpoint.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-signaling/source/KinesisVideoSignalingChannelsErrorMarshaller.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-signaling/source/KinesisVideoSignalingChannelsErrors.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-signaling/source/model/GetIceServerConfigRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-signaling/source/model/GetIceServerConfigResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-signaling/source/model/IceServer.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-signaling/source/model/SendAlexaOfferToMasterRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-signaling/source/model/SendAlexaOfferToMasterResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-kinesis-video-signaling/source/model/Service.cpp>
