# Install script for directory: C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/aws-cpp-sdk-all")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/Debug/aws-cpp-sdk-mediaconvert.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/DebugOpt/aws-cpp-sdk-mediaconvert.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/Release/aws-cpp-sdk-mediaconvert.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/RelWithDebInfo/aws-cpp-sdk-mediaconvert.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/MinSizeRel/aws-cpp-sdk-mediaconvert.lib")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/Debug/aws-cpp-sdk-mediaconvert.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/DebugOpt/aws-cpp-sdk-mediaconvert.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/Release/aws-cpp-sdk-mediaconvert.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/RelWithDebInfo/aws-cpp-sdk-mediaconvert.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/MinSizeRel/aws-cpp-sdk-mediaconvert.dll")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/pkgconfig" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert.pc")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/aws/mediaconvert" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/MediaConvertClient.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/MediaConvertEndpoint.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/MediaConvertErrorMarshaller.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/MediaConvertErrors.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/MediaConvertRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/MediaConvert_EXPORTS.h"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/aws/mediaconvert/model" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AacAudioDescriptionBroadcasterMix.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AacCodecProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AacCodingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AacRateControlMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AacRawFormat.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AacSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AacSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AacVbrQuality.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Ac3BitstreamMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Ac3CodingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Ac3DynamicRangeCompressionProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Ac3LfeFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Ac3MetadataControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Ac3Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AccelerationMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AccelerationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AccelerationStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AfdSignaling.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AiffSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AlphaBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AncillaryConvert608To708.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AncillarySourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AncillaryTerminateCaptions.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AntiAlias.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AssociateCertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AssociateCertificateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioCodec.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioCodecSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioDefaultSelection.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioLanguageCodeControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioNormalizationAlgorithm.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioNormalizationAlgorithmControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioNormalizationLoudnessLogging.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioNormalizationPeakCalculation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioNormalizationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioSelector.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioSelectorGroup.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioSelectorType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AudioTypeControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Av1AdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Av1FramerateControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Av1FramerateConversionAlgorithm.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Av1QvbrSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Av1RateControlMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Av1Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Av1SpatialAdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/AvailBlanking.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/BillingTagsSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/BurninDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/BurninSubtitleAlignment.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/BurninSubtitleBackgroundColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/BurninSubtitleFontColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/BurninSubtitleOutlineColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/BurninSubtitleShadowColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/BurninSubtitleTeletextSpacing.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CancelJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CancelJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CaptionDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CaptionDescriptionPreset.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CaptionDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CaptionDestinationType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CaptionSelector.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CaptionSourceFramerate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CaptionSourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CaptionSourceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ChannelMapping.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafAdditionalManifest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafClientCache.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafCodecSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafEncryptionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafEncryptionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafInitializationVectorInManifest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafKeyProviderType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafManifestCompression.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafManifestDurationFormat.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafMpdProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafSegmentControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafStreamInfResolution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafWriteDASHManifest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafWriteHLSManifest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmafWriteSegmentTimelineInRepresentation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmfcScte35Esam.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmfcScte35Source.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CmfcSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ColorCorrector.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ColorMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ColorSpace.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ColorSpaceConversion.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ColorSpaceUsage.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Commitment.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ContainerSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ContainerType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CreateJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CreateJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CreateJobTemplateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CreateJobTemplateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CreatePresetRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CreatePresetResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CreateQueueRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/CreateQueueResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DashAdditionalManifest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DashIsoEncryptionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DashIsoGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DashIsoHbbtvCompliance.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DashIsoMpdProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DashIsoPlaybackDeviceCompatibility.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DashIsoSegmentControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DashIsoWriteSegmentTimelineInRepresentation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DecryptionMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DeinterlaceAlgorithm.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Deinterlacer.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DeinterlacerControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DeinterlacerMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DeleteJobTemplateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DeleteJobTemplateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DeletePresetRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DeletePresetResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DeleteQueueRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DeleteQueueResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DescribeEndpointsMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DescribeEndpointsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DescribeEndpointsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DisassociateCertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DisassociateCertificateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DolbyVision.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DolbyVisionLevel6Metadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DolbyVisionLevel6Mode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DolbyVisionProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DropFrameTimecode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbNitSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbSdtSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbSubDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbSubSourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbSubtitleAlignment.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbSubtitleBackgroundColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbSubtitleFontColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbSubtitleOutlineColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbSubtitleShadowColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbSubtitleTeletextSpacing.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbSubtitlingType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/DvbTdtSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3AtmosBitstreamMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3AtmosCodingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3AtmosDialogueIntelligence.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3AtmosDynamicRangeCompressionLine.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3AtmosDynamicRangeCompressionRf.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3AtmosMeteringMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3AtmosSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3AtmosStereoDownmix.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3AtmosSurroundExMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3AttenuationControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3BitstreamMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3CodingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3DcFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3DynamicRangeCompressionLine.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3DynamicRangeCompressionRf.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3LfeControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3LfeFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3MetadataControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3PassthroughControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3PhaseControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3StereoDownmix.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3SurroundExMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Eac3SurroundMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/EmbeddedConvert608To708.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/EmbeddedDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/EmbeddedSourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/EmbeddedTerminateCaptions.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Endpoint.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/EsamManifestConfirmConditionNotification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/EsamSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/EsamSignalProcessingNotification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/F4vMoovPlacement.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/F4vSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/FileGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/FileSourceConvert608To708.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/FileSourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/FontScript.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/FrameCaptureSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/GetJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/GetJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/GetJobTemplateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/GetJobTemplateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/GetPresetRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/GetPresetResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/GetQueueRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/GetQueueResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264AdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264CodecLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264CodecProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264DynamicSubGop.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264EntropyEncoding.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264FieldEncoding.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264FlickerAdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264FramerateControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264FramerateConversionAlgorithm.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264GopBReference.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264GopSizeUnits.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264InterlaceMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264ParControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264QualityTuningLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264QvbrSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264RateControlMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264RepeatPps.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264SceneChangeDetect.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264SlowPal.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264SpatialAdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264Syntax.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264Telecine.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264TemporalAdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H264UnregisteredSeiTimecode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265AdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265AlternateTransferFunctionSei.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265CodecLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265CodecProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265DynamicSubGop.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265FlickerAdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265FramerateControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265FramerateConversionAlgorithm.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265GopBReference.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265GopSizeUnits.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265InterlaceMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265ParControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265QualityTuningLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265QvbrSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265RateControlMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265SampleAdaptiveOffsetFilterMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265SceneChangeDetect.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265SlowPal.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265SpatialAdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265Telecine.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265TemporalAdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265TemporalIds.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265Tiles.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265UnregisteredSeiTimecode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/H265WriteMp4PackagingType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Hdr10Metadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsAdMarkers.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsAdditionalManifest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsAudioOnlyContainer.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsAudioTrackType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsCaptionLanguageMapping.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsCaptionLanguageSetting.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsClientCache.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsCodecSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsDirectoryStructure.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsEncryptionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsEncryptionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsIFrameOnlyManifest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsInitializationVectorInManifest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsKeyProviderType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsManifestCompression.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsManifestDurationFormat.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsOfflineEncrypted.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsOutputSelection.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsProgramDateTime.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsSegmentControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsStreamInfResolution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HlsTimedMetadataId3Frame.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/HopDestination.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Id3Insertion.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ImageInserter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ImscDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ImscStylePassthrough.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Input.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/InputClipping.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/InputDeblockFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/InputDecryptionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/InputDenoiseFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/InputFilterEnable.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/InputPsiControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/InputRotate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/InputTemplate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/InputTimecodeSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/InsertableImage.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Job.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/JobMessages.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/JobPhase.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/JobSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/JobStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/JobTemplate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/JobTemplateListBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/JobTemplateSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/LanguageCode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ListJobTemplatesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ListJobTemplatesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ListJobsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ListJobsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ListPresetsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ListPresetsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ListQueuesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ListQueuesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ListTagsForResourceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ListTagsForResourceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsAudioBufferModel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsBufferModel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsEbpAudioInterval.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsEbpPlacement.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsEsRateInPes.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsForceTsVideoEbpOrder.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsNielsenId3.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsPcrControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsRateMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsScte35Esam.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsScte35Source.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsSegmentationMarkers.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsSegmentationStyle.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M2tsSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M3u8NielsenId3.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M3u8PcrControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M3u8Scte35Source.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/M3u8Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MotionImageInserter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MotionImageInsertionFramerate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MotionImageInsertionMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MotionImageInsertionOffset.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MotionImagePlayback.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MovClapAtom.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MovCslgAtom.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MovMpeg2FourCCControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MovPaddingControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MovReference.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MovSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mp2Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mp3RateControlMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mp3Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mp4CslgAtom.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mp4FreeSpaceBox.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mp4MoovPlacement.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mp4Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MpdCaptionContainerType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MpdScte35Esam.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MpdScte35Source.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MpdSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2AdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2CodecLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2CodecProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2DynamicSubGop.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2FramerateControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2FramerateConversionAlgorithm.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2GopSizeUnits.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2InterlaceMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2IntraDcPrecision.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2ParControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2QualityTuningLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2RateControlMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2SceneChangeDetect.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2SlowPal.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2SpatialAdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2Syntax.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2Telecine.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Mpeg2TemporalAdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MsSmoothAdditionalManifest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MsSmoothAudioDeduplication.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MsSmoothEncryptionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MsSmoothGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MsSmoothManifestEncoding.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MxfAfdSignaling.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/MxfSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/NexGuardFileMarkerSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/NielsenConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/NoiseFilterPostTemporalSharpening.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/NoiseReducer.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/NoiseReducerFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/NoiseReducerFilterSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/NoiseReducerSpatialFilterSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/NoiseReducerTemporalFilterSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/OpusSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Order.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Output.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/OutputChannelMapping.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/OutputDetail.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/OutputGroup.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/OutputGroupDetail.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/OutputGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/OutputGroupType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/OutputSdt.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/OutputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/PartnerWatermarking.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Preset.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/PresetListBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/PresetSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/PricingPlan.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ProresCodecProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ProresFramerateControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ProresFramerateConversionAlgorithm.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ProresInterlaceMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ProresParControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ProresSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ProresSlowPal.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ProresTelecine.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Queue.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/QueueListBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/QueueStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/QueueTransition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Rectangle.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/RemixSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/RenewalType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ReservationPlan.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ReservationPlanSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ReservationPlanStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ResourceTags.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/RespondToAfd.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/S3DestinationAccessControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/S3DestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/S3EncryptionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/S3ObjectCannedAcl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/S3ServerSideEncryptionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/ScalingBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/SccDestinationFramerate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/SccDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/SimulateReservedQueue.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/SpekeKeyProvider.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/SpekeKeyProviderCmaf.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/StaticKeyProvider.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/StatusUpdateInterval.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TagResourceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TagResourceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TeletextDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TeletextPageType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TeletextSourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TimecodeBurnin.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TimecodeBurninPosition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TimecodeConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TimecodeSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TimedMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TimedMetadataInsertion.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Timing.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TrackSourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TtmlDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/TtmlStylePassthrough.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Type.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/UntagResourceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/UntagResourceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/UpdateJobTemplateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/UpdateJobTemplateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/UpdatePresetRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/UpdatePresetResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/UpdateQueueRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/UpdateQueueResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/VideoCodec.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/VideoCodecSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/VideoDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/VideoDetail.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/VideoPreprocessor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/VideoSelector.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/VideoTimecodeInsertion.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/VorbisSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp8FramerateControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp8FramerateConversionAlgorithm.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp8ParControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp8QualityTuningLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp8RateControlMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp8Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp9FramerateControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp9FramerateConversionAlgorithm.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp9ParControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp9QualityTuningLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp9RateControlMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/Vp9Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/WatermarkingStrength.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/WavFormat.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/include/aws/mediaconvert/model/WavSettings.h"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-targets.cmake")
    file(DIFFERENT EXPORT_FILE_CHANGED FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-targets.cmake"
         "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-targets.cmake")
    if(EXPORT_FILE_CHANGED)
      file(GLOB OLD_CONFIG_FILES "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-targets-*.cmake")
      if(OLD_CONFIG_FILES)
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-targets.cmake\" will be replaced.  Removing files [${OLD_CONFIG_FILES}].")
        file(REMOVE ${OLD_CONFIG_FILES})
      endif()
    endif()
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-mediaconvert" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-targets.cmake")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-mediaconvert" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-targets-debug.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-mediaconvert" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-targets-debugopt.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-mediaconvert" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-targets-minsizerel.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-mediaconvert" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-targets-relwithdebinfo.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-mediaconvert" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-targets-release.cmake")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xDevelx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-mediaconvert" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-config.cmake"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-mediaconvert/aws-cpp-sdk-mediaconvert-config-version.cmake"
    )
endif()

