# Install script for directory: C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/aws-cpp-sdk-all")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/Debug/aws-cpp-sdk-sagemaker.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/DebugOpt/aws-cpp-sdk-sagemaker.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/Release/aws-cpp-sdk-sagemaker.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/RelWithDebInfo/aws-cpp-sdk-sagemaker.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/MinSizeRel/aws-cpp-sdk-sagemaker.lib")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/Debug/aws-cpp-sdk-sagemaker.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/DebugOpt/aws-cpp-sdk-sagemaker.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/Release/aws-cpp-sdk-sagemaker.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/RelWithDebInfo/aws-cpp-sdk-sagemaker.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/MinSizeRel/aws-cpp-sdk-sagemaker.dll")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/pkgconfig" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker.pc")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/aws/sagemaker" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/SageMakerClient.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/SageMakerEndpoint.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/SageMakerErrorMarshaller.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/SageMakerErrors.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/SageMakerRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/SageMaker_EXPORTS.h"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/aws/sagemaker/model" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AddTagsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AddTagsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AlgorithmSortBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AlgorithmSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AlgorithmStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AlgorithmStatusDetails.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AlgorithmStatusItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AlgorithmSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AlgorithmValidationProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AlgorithmValidationSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AnnotationConsolidationConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AppDetails.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AppInstanceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AppSortKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AppSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AppStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AppType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AssemblyType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AssociateTrialComponentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AssociateTrialComponentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AuthMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLCandidate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLCandidateStep.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLChannel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLContainerDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLDataSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLJobArtifacts.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLJobCompletionCriteria.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLJobConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLJobObjective.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLJobObjectiveType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLJobSecondaryStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLJobStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLJobSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLMetricEnum.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLOutputDataConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLS3DataSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLS3DataType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLSecurityConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLSortBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AutoMLSortOrder.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/AwsManagedHumanLoopRequestSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/BatchStrategy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/BooleanOperator.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CandidateSortBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CandidateStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CandidateStepType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CaptureContentTypeHeader.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CaptureMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CaptureOption.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CaptureStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CategoricalParameterRange.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CategoricalParameterRangeSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/Channel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ChannelSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CheckpointConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CodeRepositorySortBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CodeRepositorySortOrder.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CodeRepositorySummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CognitoConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CognitoMemberDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CollectionConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CompilationJobStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CompilationJobSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CompressionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ContainerDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ContainerMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ContentClassifier.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ContinuousParameterRange.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ContinuousParameterRangeSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateAlgorithmRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateAlgorithmResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateAppRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateAppResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateAutoMLJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateAutoMLJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateCodeRepositoryRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateCodeRepositoryResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateCompilationJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateCompilationJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateDomainRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateDomainResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateEndpointConfigRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateEndpointConfigResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateEndpointRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateEndpointResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateExperimentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateExperimentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateFlowDefinitionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateFlowDefinitionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateHumanTaskUiRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateHumanTaskUiResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateHyperParameterTuningJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateHyperParameterTuningJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateLabelingJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateLabelingJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateModelPackageRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateModelPackageResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateModelRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateModelResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateMonitoringScheduleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateMonitoringScheduleResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateNotebookInstanceLifecycleConfigRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateNotebookInstanceLifecycleConfigResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateNotebookInstanceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateNotebookInstanceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreatePresignedDomainUrlRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreatePresignedDomainUrlResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreatePresignedNotebookInstanceUrlRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreatePresignedNotebookInstanceUrlResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateProcessingJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateProcessingJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateTrainingJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateTrainingJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateTransformJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateTransformJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateTrialComponentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateTrialComponentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateTrialRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateTrialResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateUserProfileRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateUserProfileResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateWorkforceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateWorkforceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateWorkteamRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/CreateWorkteamResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DataCaptureConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DataCaptureConfigSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DataProcessing.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DataSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DebugHookConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DebugRuleConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DebugRuleEvaluationStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteAlgorithmRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteAppRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteCodeRepositoryRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteDomainRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteEndpointConfigRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteEndpointRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteExperimentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteExperimentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteFlowDefinitionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteFlowDefinitionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteHumanTaskUiRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteHumanTaskUiResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteModelPackageRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteModelRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteMonitoringScheduleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteNotebookInstanceLifecycleConfigRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteNotebookInstanceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteTagsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteTagsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteTrialComponentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteTrialComponentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteTrialRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteTrialResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteUserProfileRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteWorkforceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteWorkforceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteWorkteamRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeleteWorkteamResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DeployedImage.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeAlgorithmRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeAlgorithmResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeAppRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeAppResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeAutoMLJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeAutoMLJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeCodeRepositoryRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeCodeRepositoryResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeCompilationJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeCompilationJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeDomainRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeDomainResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeEndpointConfigRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeEndpointConfigResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeEndpointRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeEndpointResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeExperimentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeExperimentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeFlowDefinitionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeFlowDefinitionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeHumanTaskUiRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeHumanTaskUiResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeHyperParameterTuningJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeHyperParameterTuningJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeLabelingJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeLabelingJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeModelPackageRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeModelPackageResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeModelRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeModelResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeMonitoringScheduleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeMonitoringScheduleResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeNotebookInstanceLifecycleConfigRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeNotebookInstanceLifecycleConfigResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeNotebookInstanceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeNotebookInstanceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeProcessingJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeProcessingJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeSubscribedWorkteamRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeSubscribedWorkteamResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeTrainingJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeTrainingJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeTransformJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeTransformJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeTrialComponentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeTrialComponentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeTrialRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeTrialResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeUserProfileRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeUserProfileResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeWorkforceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeWorkforceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeWorkteamRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DescribeWorkteamResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DesiredWeightAndCapacity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DetailedAlgorithmStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DetailedModelPackageStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DirectInternetAccess.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DisassociateTrialComponentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DisassociateTrialComponentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DomainDetails.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/DomainStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/EndpointConfigSortKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/EndpointConfigSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/EndpointInput.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/EndpointSortKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/EndpointStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/EndpointSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ExecutionStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/Experiment.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ExperimentConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ExperimentSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ExperimentSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/FileSystemAccessMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/FileSystemDataSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/FileSystemType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/Filter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/FinalAutoMLJobObjectiveMetric.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/FinalHyperParameterTuningJobObjectiveMetric.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/FlowDefinitionOutputConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/FlowDefinitionStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/FlowDefinitionSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/Framework.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/GetSearchSuggestionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/GetSearchSuggestionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/GitConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/GitConfigForUpdate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HumanLoopActivationConditionsConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HumanLoopActivationConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HumanLoopConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HumanLoopRequestSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HumanTaskConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HumanTaskUiStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HumanTaskUiSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterAlgorithmSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterScalingType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterTrainingJobDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterTrainingJobSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterTuningJobConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterTuningJobObjective.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterTuningJobObjectiveType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterTuningJobSortByOptions.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterTuningJobStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterTuningJobStrategyType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterTuningJobSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterTuningJobWarmStartConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/HyperParameterTuningJobWarmStartType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ImageConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/InferenceSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/InputConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/InstanceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/IntegerParameterRange.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/IntegerParameterRangeSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/JoinSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/JupyterServerAppSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/KernelGatewayAppSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelCounters.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelCountersForWorkteam.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobAlgorithmsConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobDataAttributes.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobDataSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobForWorkteamSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobInputConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobOutput.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobOutputConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobResourceConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobS3DataSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobStoppingConditions.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/LabelingJobSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListAlgorithmsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListAlgorithmsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListAppsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListAppsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListAutoMLJobsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListAutoMLJobsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListCandidatesForAutoMLJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListCandidatesForAutoMLJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListCodeRepositoriesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListCodeRepositoriesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListCompilationJobsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListCompilationJobsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListCompilationJobsSortBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListDomainsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListDomainsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListEndpointConfigsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListEndpointConfigsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListEndpointsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListEndpointsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListExperimentsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListExperimentsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListFlowDefinitionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListFlowDefinitionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListHumanTaskUisRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListHumanTaskUisResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListHyperParameterTuningJobsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListHyperParameterTuningJobsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListLabelingJobsForWorkteamRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListLabelingJobsForWorkteamResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListLabelingJobsForWorkteamSortByOptions.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListLabelingJobsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListLabelingJobsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListModelPackagesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListModelPackagesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListModelsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListModelsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListMonitoringExecutionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListMonitoringExecutionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListMonitoringSchedulesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListMonitoringSchedulesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListNotebookInstanceLifecycleConfigsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListNotebookInstanceLifecycleConfigsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListNotebookInstancesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListNotebookInstancesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListProcessingJobsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListProcessingJobsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListSubscribedWorkteamsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListSubscribedWorkteamsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTagsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTagsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTrainingJobsForHyperParameterTuningJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTrainingJobsForHyperParameterTuningJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTrainingJobsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTrainingJobsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTransformJobsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTransformJobsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTrialComponentsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTrialComponentsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTrialsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListTrialsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListUserProfilesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListUserProfilesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListWorkforcesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListWorkforcesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListWorkforcesSortByOptions.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListWorkteamsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListWorkteamsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ListWorkteamsSortByOptions.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MemberDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MetricData.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MetricDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelArtifacts.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelClientConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelPackageContainerDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelPackageSortBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelPackageStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelPackageStatusDetails.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelPackageStatusItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelPackageSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelPackageValidationProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelPackageValidationSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelSortKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ModelSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringAppSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringBaselineConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringClusterConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringConstraintsResource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringExecutionSortKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringExecutionSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringInput.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringJobDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringOutput.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringOutputConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringResources.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringS3Output.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringScheduleConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringScheduleSortKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringScheduleSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringStatisticsResource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/MonitoringStoppingCondition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NestedFilters.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NetworkConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NotebookInstanceAcceleratorType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NotebookInstanceLifecycleConfigSortKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NotebookInstanceLifecycleConfigSortOrder.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NotebookInstanceLifecycleConfigSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NotebookInstanceLifecycleHook.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NotebookInstanceSortKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NotebookInstanceSortOrder.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NotebookInstanceStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NotebookInstanceSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NotebookOutputOption.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/NotificationConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ObjectiveStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ObjectiveStatusCounters.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/OidcConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/OidcConfigForResponse.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/OidcMemberDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/Operator.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/OrderKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/OutputConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/OutputDataConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ParameterRange.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ParameterRanges.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ParameterType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/Parent.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ParentHyperParameterTuningJob.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProblemType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingClusterConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingInput.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingInstanceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingJob.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingJobStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingJobSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingOutput.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingOutputConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingResources.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingS3CompressionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingS3DataDistributionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingS3DataType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingS3Input.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingS3InputMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingS3Output.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingS3UploadMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProcessingStoppingCondition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProductionVariant.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProductionVariantAcceleratorType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProductionVariantInstanceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ProductionVariantSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/PropertyNameQuery.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/PropertyNameSuggestion.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/PublicWorkforceTaskPrice.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/RecordWrapper.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/RenderUiTemplateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/RenderUiTemplateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/RenderableTask.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/RenderingError.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/RepositoryAccessMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ResolvedAttributes.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ResourceConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ResourceLimits.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ResourceSpec.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ResourceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/RetentionPolicy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/RetentionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/RootAccess.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/RuleEvaluationStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/S3DataDistribution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/S3DataSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/S3DataType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ScheduleConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ScheduleStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SearchExpression.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SearchRecord.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SearchRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SearchResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SearchSortOrder.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SecondaryStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SecondaryStatusTransition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SharingSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/ShuffleConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SortBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SortExperimentsBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SortOrder.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SortTrialComponentsBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SortTrialsBy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SourceAlgorithm.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SourceAlgorithmSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SourceIpConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SplitType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StartMonitoringScheduleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StartNotebookInstanceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StopAutoMLJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StopCompilationJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StopHyperParameterTuningJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StopLabelingJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StopMonitoringScheduleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StopNotebookInstanceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StopProcessingJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StopTrainingJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StopTransformJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/StoppingCondition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SubscribedWorkteam.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/SuggestionQuery.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/Tag.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TargetDevice.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TargetPlatform.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TargetPlatformAccelerator.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TargetPlatformArch.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TargetPlatformOs.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TensorBoardAppSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TensorBoardOutputConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrainingInputMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrainingInstanceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrainingJob.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrainingJobDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrainingJobEarlyStoppingType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrainingJobSortByOptions.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrainingJobStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrainingJobStatusCounters.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrainingJobSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrainingSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TransformDataSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TransformInput.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TransformInstanceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TransformJob.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TransformJobDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TransformJobStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TransformJobSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TransformOutput.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TransformResources.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TransformS3DataSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/Trial.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialComponent.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialComponentArtifact.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialComponentMetricSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialComponentParameterValue.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialComponentPrimaryStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialComponentSimpleSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialComponentSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialComponentSourceDetail.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialComponentStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialComponentSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TrialSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/TuningJobCompletionCriteria.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/USD.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UiConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UiTemplate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UiTemplateInfo.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateCodeRepositoryRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateCodeRepositoryResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateDomainRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateDomainResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateEndpointRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateEndpointResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateEndpointWeightsAndCapacitiesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateEndpointWeightsAndCapacitiesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateExperimentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateExperimentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateMonitoringScheduleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateMonitoringScheduleResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateNotebookInstanceLifecycleConfigRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateNotebookInstanceLifecycleConfigResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateNotebookInstanceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateNotebookInstanceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateTrialComponentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateTrialComponentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateTrialRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateTrialResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateUserProfileRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateUserProfileResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateWorkforceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateWorkforceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateWorkteamRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UpdateWorkteamResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UserContext.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UserProfileDetails.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UserProfileSortKey.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UserProfileStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/UserSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/VariantProperty.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/VariantPropertyType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/VpcConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/Workforce.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/include/aws/sagemaker/model/Workteam.h"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-targets.cmake")
    file(DIFFERENT EXPORT_FILE_CHANGED FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-targets.cmake"
         "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-targets.cmake")
    if(EXPORT_FILE_CHANGED)
      file(GLOB OLD_CONFIG_FILES "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-targets-*.cmake")
      if(OLD_CONFIG_FILES)
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-targets.cmake\" will be replaced.  Removing files [${OLD_CONFIG_FILES}].")
        file(REMOVE ${OLD_CONFIG_FILES})
      endif()
    endif()
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-sagemaker" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-targets.cmake")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-sagemaker" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-targets-debug.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-sagemaker" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-targets-debugopt.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-sagemaker" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-targets-minsizerel.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-sagemaker" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-targets-relwithdebinfo.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-sagemaker" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-targets-release.cmake")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xDevelx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-sagemaker" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-config.cmake"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker/aws-cpp-sdk-sagemaker-config-version.cmake"
    )
endif()

