// Unity Build generated by CMake
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/MarketplaceMeteringClient.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/MarketplaceMeteringEndpoint.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/MarketplaceMeteringErrorMarshaller.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/MarketplaceMeteringErrors.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/model/BatchMeterUsageRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/model/BatchMeterUsageResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/model/MeterUsageRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/model/MeterUsageResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/model/RegisterUsageRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/model/RegisterUsageResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/model/ResolveCustomerRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/model/ResolveCustomerResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/model/UsageRecord.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/model/UsageRecordResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-meteringmarketplace/source/model/UsageRecordResultStatus.cpp>
