// Unity Build generated by CMake
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplace-entitlement/source/MarketplaceEntitlementServiceClient.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplace-entitlement/source/MarketplaceEntitlementServiceEndpoint.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplace-entitlement/source/MarketplaceEntitlementServiceErrorMarshaller.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplace-entitlement/source/MarketplaceEntitlementServiceErrors.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplace-entitlement/source/model/Entitlement.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplace-entitlement/source/model/EntitlementValue.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplace-entitlement/source/model/GetEntitlementFilterName.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplace-entitlement/source/model/GetEntitlementsRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-marketplace-entitlement/source/model/GetEntitlementsResult.cpp>
