# Install script for directory: C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/aws-cpp-sdk-all")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/Debug/aws-cpp-sdk-medialive.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/DebugOpt/aws-cpp-sdk-medialive.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/Release/aws-cpp-sdk-medialive.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/RelWithDebInfo/aws-cpp-sdk-medialive.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/MinSizeRel/aws-cpp-sdk-medialive.lib")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/Debug/aws-cpp-sdk-medialive.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/DebugOpt/aws-cpp-sdk-medialive.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/Release/aws-cpp-sdk-medialive.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/RelWithDebInfo/aws-cpp-sdk-medialive.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/MinSizeRel/aws-cpp-sdk-medialive.dll")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/pkgconfig" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive.pc")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/aws/medialive" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/MediaLiveClient.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/MediaLiveEndpoint.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/MediaLiveErrorMarshaller.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/MediaLiveErrors.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/MediaLiveRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/MediaLive_EXPORTS.h"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/aws/medialive/model" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AacCodingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AacInputType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AacProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AacRateControlMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AacRawFormat.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AacSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AacSpec.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AacVbrQuality.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Ac3BitstreamMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Ac3CodingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Ac3DrcProfile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Ac3LfeFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Ac3MetadataControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Ac3Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AcceptHeader.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AfdSignaling.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ArchiveContainerSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ArchiveGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ArchiveOutputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AribDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AribSourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioChannelMapping.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioCodecSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioDescriptionAudioTypeControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioDescriptionLanguageCodeControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioLanguageSelection.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioLanguageSelectionPolicy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioNormalizationAlgorithm.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioNormalizationAlgorithmControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioNormalizationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioOnlyHlsSegmentType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioOnlyHlsSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioOnlyHlsTrackType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioPidSelection.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioSelector.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioSelectorSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioTrack.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioTrackSelection.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AudioType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AuthenticationScheme.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AutomaticInputFailoverSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AvailBlanking.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AvailBlankingState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AvailConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/AvailSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BatchScheduleActionCreateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BatchScheduleActionCreateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BatchScheduleActionDeleteRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BatchScheduleActionDeleteResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BatchUpdateScheduleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BatchUpdateScheduleResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BlackoutSlate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BlackoutSlateNetworkEndBlackout.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BlackoutSlateState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BurnInAlignment.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BurnInBackgroundColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BurnInDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BurnInFontColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BurnInOutlineColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BurnInShadowColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/BurnInTeletextGridControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CaptionDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CaptionDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CaptionLanguageMapping.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CaptionSelector.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CaptionSelectorSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Channel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ChannelClass.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ChannelEgressEndpoint.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ChannelState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ChannelSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ColorSpacePassthroughSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ContentType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CreateChannelRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CreateChannelResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CreateInputRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CreateInputResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CreateInputSecurityGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CreateInputSecurityGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CreateMultiplexProgramRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CreateMultiplexProgramResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CreateMultiplexRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CreateMultiplexResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/CreateTagsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteChannelRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteChannelResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteInputRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteInputResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteInputSecurityGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteInputSecurityGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteMultiplexProgramRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteMultiplexProgramResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteMultiplexRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteMultiplexResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteReservationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteReservationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteScheduleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteScheduleResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeleteTagsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeChannelRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeChannelResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeInputDeviceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeInputDeviceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeInputDeviceThumbnailRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeInputDeviceThumbnailResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeInputRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeInputResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeInputSecurityGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeInputSecurityGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeMultiplexProgramRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeMultiplexProgramResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeMultiplexRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeMultiplexResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeOfferingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeOfferingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeReservationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeReservationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeScheduleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DescribeScheduleResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DeviceSettingsSyncState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbNitSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbSdtOutputSdt.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbSdtSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbSubDestinationAlignment.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbSubDestinationBackgroundColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbSubDestinationFontColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbSubDestinationOutlineColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbSubDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbSubDestinationShadowColor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbSubDestinationTeletextGridControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbSubSourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/DvbTdtSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3AttenuationControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3BitstreamMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3CodingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3DcFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3DrcLine.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3DrcRf.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3LfeControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3LfeFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3MetadataControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3PassthroughControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3PhaseControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3StereoDownmix.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3SurroundExMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Eac3SurroundMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/EbuTtDDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/EbuTtDDestinationStyleControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/EbuTtDFillLineGapControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/EmbeddedConvert608To708.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/EmbeddedDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/EmbeddedPlusScte20DestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/EmbeddedScte20Detection.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/EmbeddedSourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/EncoderSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FeatureActivations.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FeatureActivationsInputPrepareScheduleActions.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FecOutputIncludeFec.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FecOutputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FixedAfd.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FixedModeScheduleActionStartSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Fmp4HlsSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Fmp4NielsenId3Behavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Fmp4TimedMetadataBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FollowModeScheduleActionStartSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FollowPoint.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FrameCaptureGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FrameCaptureIntervalUnit.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FrameCaptureOutputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/FrameCaptureSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/GlobalConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/GlobalConfigurationInputEndAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/GlobalConfigurationLowFramerateInputs.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/GlobalConfigurationOutputLockingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/GlobalConfigurationOutputTimingSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264AdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264ColorMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264ColorSpaceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264EntropyEncoding.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264FilterSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264FlickerAq.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264ForceFieldPictures.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264FramerateControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264GopBReference.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264GopSizeUnits.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264Level.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264LookAheadRateControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264ParControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264Profile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264QualityLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264RateControlMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264ScanType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264SceneChangeDetect.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264SpatialAq.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264SubGopLength.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264Syntax.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264TemporalAq.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H264TimecodeInsertionBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265AdaptiveQuantization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265AlternativeTransferFunction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265ColorMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265ColorSpaceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265FilterSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265FlickerAq.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265GopSizeUnits.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265Level.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265LookAheadRateControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265Profile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265RateControlMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265ScanType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265SceneChangeDetect.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265Tier.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/H265TimecodeInsertionBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Hdr10Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsAdMarkers.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsAkamaiHttpTransferMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsAkamaiSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsBasicPutSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsCaptionLanguageSetting.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsCdnSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsClientCache.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsCodecSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsDirectoryStructure.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsEncryptionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsH265PackagingType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsId3SegmentTaggingScheduleActionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsId3SegmentTaggingState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsInputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsIvInManifest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsIvSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsManifestCompression.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsManifestDurationFormat.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsMediaStoreSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsMediaStoreStorageClass.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsOutputSelection.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsOutputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsProgramDateTime.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsRedundantManifest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsSegmentationMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsStreamInfResolution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsTimedMetadataId3Frame.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsTimedMetadataScheduleActionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsTsFileMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsWebdavHttpTransferMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/HlsWebdavSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/IFrameOnlyPlaylistType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ImmediateModeScheduleActionStartSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Input.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputAttachment.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputChannelLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputClass.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputClippingSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputCodec.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeblockFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDenoiseFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDestination.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDestinationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDestinationVpc.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceActiveInput.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceConfigurableSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceConfiguredInput.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceConnectionState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceHdSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceIpScheme.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceNetworkSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceScanType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputDeviceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputFilter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputLocation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputLossActionForHlsOut.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputLossActionForMsSmoothOut.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputLossActionForRtmpOut.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputLossActionForUdpOut.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputLossBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputLossImageType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputMaximumBitrate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputPreference.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputPrepareScheduleActionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputResolution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputSecurityGroup.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputSecurityGroupState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputSourceEndBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputSourceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputSourceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputSwitchScheduleActionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputTimecodeSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputVpcRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputWhitelistRule.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/InputWhitelistRuleCidr.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/KeyProviderSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/LastFrameClippingBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListChannelsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListChannelsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListInputDevicesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListInputDevicesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListInputSecurityGroupsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListInputSecurityGroupsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListInputsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListInputsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListMultiplexProgramsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListMultiplexProgramsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListMultiplexesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListMultiplexesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListOfferingsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListOfferingsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListReservationsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListReservationsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListTagsForResourceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ListTagsForResourceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/LogLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsAbsentInputAudioBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsArib.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsAribCaptionsPidControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsAudioBufferModel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsAudioInterval.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsAudioStreamType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsBufferModel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsCcDescriptor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsEbifControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsEbpPlacement.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsEsRateInPes.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsKlv.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsNielsenId3Behavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsPcrControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsRateMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsScte35Control.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsSegmentationMarkers.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsSegmentationStyle.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M2tsTimedMetadataBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M3u8NielsenId3Behavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M3u8PcrControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M3u8Scte35Behavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M3u8Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/M3u8TimedMetadataBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MediaConnectFlow.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MediaConnectFlowRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MediaPackageGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MediaPackageOutputDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MediaPackageOutputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Mp2CodingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Mp2Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MsSmoothGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MsSmoothH265PackagingType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MsSmoothOutputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Multiplex.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexMediaConnectOutputDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexOutputDestination.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexOutputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexProgram.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexProgramChannelDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexProgramPacketIdentifiersMap.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexProgramServiceDescriptor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexProgramSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexProgramSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexSettingsSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexStatmuxVideoSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/MultiplexVideoSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/NetworkInputServerValidation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/NetworkInputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/NielsenConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/NielsenPcmToId3TaggingState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Offering.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/OfferingDurationUnits.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/OfferingType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Output.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/OutputDestination.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/OutputDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/OutputGroup.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/OutputGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/OutputLocationRef.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/OutputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/PassThroughSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/PauseStateScheduleActionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/PipelineDetail.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/PipelineId.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/PipelinePauseStateSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/PreferredChannelPipeline.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/PurchaseOfferingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/PurchaseOfferingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Rec601Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Rec709Settings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/RemixSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Reservation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ReservationCodec.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ReservationMaximumBitrate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ReservationMaximumFramerate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ReservationResolution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ReservationResourceSpecification.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ReservationResourceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ReservationSpecialFeature.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ReservationState.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ReservationVideoQuality.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/RtmpCacheFullBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/RtmpCaptionData.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/RtmpCaptionInfoDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/RtmpGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/RtmpOutputCertificateMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/RtmpOutputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ScheduleAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ScheduleActionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ScheduleActionStartSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte20Convert608To708.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte20PlusEmbeddedDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte20SourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte27DestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte27SourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35AposNoRegionalBlackoutBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35AposWebDeliveryAllowedBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35ArchiveAllowedFlag.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35DeliveryRestrictions.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35Descriptor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35DescriptorSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35DeviceRestrictions.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35NoRegionalBlackoutFlag.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35ReturnToNetworkScheduleActionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35SegmentationCancelIndicator.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35SegmentationDescriptor.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35SpliceInsert.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35SpliceInsertNoRegionalBlackoutBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35SpliceInsertScheduleActionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35SpliceInsertWebDeliveryAllowedBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35TimeSignalApos.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35TimeSignalScheduleActionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Scte35WebDeliveryAllowedFlag.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/SmoothGroupAudioOnlyTimecodeControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/SmoothGroupCertificateMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/SmoothGroupEventIdMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/SmoothGroupEventStopBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/SmoothGroupSegmentationMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/SmoothGroupSparseTrackType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/SmoothGroupStreamManifestBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/SmoothGroupTimestampOffsetMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/Smpte2038DataPreference.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/SmpteTtDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StandardHlsSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StartChannelRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StartChannelResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StartMultiplexRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StartMultiplexResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StartTimecode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StaticImageActivateScheduleActionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StaticImageDeactivateScheduleActionSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StaticKeySettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StopChannelRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StopChannelResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StopMultiplexRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StopMultiplexResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/StopTimecode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/TeletextDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/TeletextSourceSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/TemporalFilterPostFilterSharpening.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/TemporalFilterSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/TemporalFilterStrength.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/TimecodeConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/TimecodeConfigSource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/TtmlDestinationSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/TtmlDestinationStyleControl.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UdpContainerSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UdpGroupSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UdpOutputSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UdpTimedMetadataId3Frame.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UnprocessableEntityException.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateChannelClassRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateChannelClassResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateChannelRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateChannelResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateInputDeviceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateInputDeviceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateInputRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateInputResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateInputSecurityGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateInputSecurityGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateMultiplexProgramRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateMultiplexProgramResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateMultiplexRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateMultiplexResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateReservationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/UpdateReservationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/ValidationError.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/VideoCodecSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/VideoDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/VideoDescriptionRespondToAfd.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/VideoDescriptionScalingBehavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/VideoSelector.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/VideoSelectorColorSpace.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/VideoSelectorColorSpaceUsage.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/VideoSelectorPid.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/VideoSelectorProgramId.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/VideoSelectorSettings.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/include/aws/medialive/model/WebvttDestinationSettings.h"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-targets.cmake")
    file(DIFFERENT EXPORT_FILE_CHANGED FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-targets.cmake"
         "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-targets.cmake")
    if(EXPORT_FILE_CHANGED)
      file(GLOB OLD_CONFIG_FILES "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-targets-*.cmake")
      if(OLD_CONFIG_FILES)
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-targets.cmake\" will be replaced.  Removing files [${OLD_CONFIG_FILES}].")
        file(REMOVE ${OLD_CONFIG_FILES})
      endif()
    endif()
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-medialive" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-targets.cmake")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-medialive" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-targets-debug.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-medialive" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-targets-debugopt.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-medialive" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-targets-minsizerel.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-medialive" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-targets-relwithdebinfo.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-medialive" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-targets-release.cmake")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xDevelx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-medialive" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-config.cmake"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-medialive/aws-cpp-sdk-medialive-config-version.cmake"
    )
endif()

