// Unity Build generated by CMake
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/IoTJobsDataPlaneClient.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/IoTJobsDataPlaneEndpoint.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/IoTJobsDataPlaneErrorMarshaller.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/IoTJobsDataPlaneErrors.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/DescribeJobExecutionRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/DescribeJobExecutionResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/GetPendingJobExecutionsRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/GetPendingJobExecutionsResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/JobExecution.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/JobExecutionState.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/JobExecutionStatus.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/JobExecutionSummary.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/StartNextPendingJobExecutionRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/StartNextPendingJobExecutionResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/ThrottlingException.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/UpdateJobExecutionRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot-jobs-data/source/model/UpdateJobExecutionResult.cpp>
