// Unity Build generated by CMake
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker-runtime/source/SageMakerRuntimeClient.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker-runtime/source/SageMakerRuntimeEndpoint.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker-runtime/source/SageMakerRuntimeErrorMarshaller.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker-runtime/source/SageMakerRuntimeErrors.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker-runtime/source/model/InvokeEndpointRequest.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker-runtime/source/model/InvokeEndpointResult.cpp>
#include <C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-sagemaker-runtime/source/model/ModelError.cpp>
