# Install script for directory: C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "C:/Program Files (x86)/aws-cpp-sdk-all")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "FALSE")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/Debug/aws-cpp-sdk-iot.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/DebugOpt/aws-cpp-sdk-iot.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/Release/aws-cpp-sdk-iot.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/RelWithDebInfo/aws-cpp-sdk-iot.lib")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE STATIC_LIBRARY OPTIONAL FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/MinSizeRel/aws-cpp-sdk-iot.lib")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/Debug/aws-cpp-sdk-iot.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/DebugOpt/aws-cpp-sdk-iot.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/Release/aws-cpp-sdk-iot.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/RelWithDebInfo/aws-cpp-sdk-iot.dll")
  elseif("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/bin" TYPE SHARED_LIBRARY FILES "C:/Users/isaac/Projects/aws-sdk-cpp/bin/MinSizeRel/aws-cpp-sdk-iot.dll")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/pkgconfig" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/aws-cpp-sdk-iot.pc")
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/aws/iot" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/IoTClient.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/IoTEndpoint.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/IoTErrorMarshaller.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/IoTErrors.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/IoTRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/IoT_EXPORTS.h"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/include/aws/iot/model" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AbortAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AbortConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AbortCriteria.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AcceptCertificateTransferRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Action.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ActionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ActiveViolation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AddThingToBillingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AddThingToBillingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AddThingToThingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AddThingToThingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AddThingsToThingGroupParams.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AlertTarget.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AlertTargetType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Allowed.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AssetPropertyTimestamp.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AssetPropertyValue.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AssetPropertyVariant.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AssociateTargetsWithJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AssociateTargetsWithJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AttachPolicyRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AttachSecurityProfileRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AttachSecurityProfileResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AttachThingPrincipalRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AttachThingPrincipalResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AttributePayload.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditCheckConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditCheckDetails.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditCheckRunStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditFinding.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditFindingSeverity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditFrequency.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditMitigationActionExecutionMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditMitigationActionsExecutionStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditMitigationActionsTaskMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditMitigationActionsTaskStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditMitigationActionsTaskTarget.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditNotificationTarget.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditNotificationType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditSuppression.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditTaskMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditTaskStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuditTaskType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuthDecision.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuthInfo.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuthResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuthorizerConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuthorizerDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuthorizerStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AuthorizerSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AutoRegistrationStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AwsJobAbortConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AwsJobAbortCriteria.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AwsJobAbortCriteriaAbortAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AwsJobAbortCriteriaFailureType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AwsJobExecutionsRolloutConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AwsJobExponentialRolloutRate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AwsJobPresignedUrlConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AwsJobRateIncreaseCriteria.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/AwsJobTimeoutConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Behavior.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/BehaviorCriteria.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/BillingGroupMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/BillingGroupProperties.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CACertificate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CACertificateDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CACertificateStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CACertificateUpdateAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CancelAuditMitigationActionsTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CancelAuditMitigationActionsTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CancelAuditTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CancelAuditTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CancelCertificateTransferRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CancelJobExecutionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CancelJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CancelJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CannedAccessControlList.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Certificate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CertificateDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CertificateMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CertificateStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CertificateValidity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ClearDefaultAuthorizerRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ClearDefaultAuthorizerResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CloudwatchAlarmAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CloudwatchLogsAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CloudwatchMetricAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CodeSigning.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CodeSigningCertificateChain.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CodeSigningSignature.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ComparisonOperator.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Configuration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ConfirmTopicRuleDestinationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ConfirmTopicRuleDestinationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateAuditSuppressionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateAuditSuppressionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateAuthorizerRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateAuthorizerResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateBillingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateBillingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateCertificateFromCsrRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateCertificateFromCsrResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateDimensionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateDimensionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateDomainConfigurationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateDomainConfigurationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateDynamicThingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateDynamicThingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateKeysAndCertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateKeysAndCertificateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateMitigationActionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateMitigationActionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateOTAUpdateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateOTAUpdateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreatePolicyRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreatePolicyResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreatePolicyVersionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreatePolicyVersionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateProvisioningClaimRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateProvisioningClaimResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateProvisioningTemplateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateProvisioningTemplateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateProvisioningTemplateVersionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateProvisioningTemplateVersionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateRoleAliasRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateRoleAliasResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateScheduledAuditRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateScheduledAuditResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateSecurityProfileRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateSecurityProfileResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateStreamRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateStreamResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateThingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateThingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateThingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateThingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateThingTypeRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateThingTypeResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateTopicRuleDestinationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateTopicRuleDestinationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CreateTopicRuleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/CustomCodeSigning.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DayOfWeek.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteAccountAuditConfigurationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteAccountAuditConfigurationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteAuditSuppressionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteAuditSuppressionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteAuthorizerRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteAuthorizerResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteBillingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteBillingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteCACertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteCACertificateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteCertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteDimensionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteDimensionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteDomainConfigurationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteDomainConfigurationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteDynamicThingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteDynamicThingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteJobExecutionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteMitigationActionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteMitigationActionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteOTAUpdateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteOTAUpdateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeletePolicyRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeletePolicyVersionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteProvisioningTemplateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteProvisioningTemplateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteProvisioningTemplateVersionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteProvisioningTemplateVersionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteRegistrationCodeRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteRegistrationCodeResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteRoleAliasRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteRoleAliasResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteScheduledAuditRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteScheduledAuditResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteSecurityProfileRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteSecurityProfileResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteStreamRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteStreamResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteThingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteThingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteThingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteThingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteThingTypeRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteThingTypeResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteTopicRuleDestinationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteTopicRuleDestinationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteTopicRuleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeleteV2LoggingLevelRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Denied.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeprecateThingTypeRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeprecateThingTypeResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAccountAuditConfigurationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAccountAuditConfigurationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAuditFindingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAuditFindingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAuditMitigationActionsTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAuditMitigationActionsTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAuditSuppressionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAuditSuppressionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAuditTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAuditTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAuthorizerRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeAuthorizerResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeBillingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeBillingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeCACertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeCACertificateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeCertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeCertificateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeDefaultAuthorizerRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeDefaultAuthorizerResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeDimensionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeDimensionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeDomainConfigurationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeDomainConfigurationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeEndpointRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeEndpointResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeEventConfigurationsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeEventConfigurationsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeIndexRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeIndexResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeJobExecutionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeJobExecutionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeMitigationActionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeMitigationActionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeProvisioningTemplateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeProvisioningTemplateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeProvisioningTemplateVersionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeProvisioningTemplateVersionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeRoleAliasRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeRoleAliasResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeScheduledAuditRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeScheduledAuditResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeSecurityProfileRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeSecurityProfileResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeStreamRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeStreamResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeThingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeThingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeThingRegistrationTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeThingRegistrationTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeThingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeThingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeThingTypeRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DescribeThingTypeResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Destination.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DetachPolicyRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DetachSecurityProfileRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DetachSecurityProfileResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DetachThingPrincipalRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DetachThingPrincipalResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DeviceCertificateUpdateAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DimensionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DimensionValueOperator.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DisableTopicRuleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DomainConfigurationStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DomainConfigurationSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DomainType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DynamicGroupStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DynamoDBAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DynamoDBv2Action.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/DynamoKeyType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/EffectivePolicy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ElasticsearchAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/EnableIoTLoggingParams.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/EnableTopicRuleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ErrorInfo.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/EventType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ExplicitDeny.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ExponentialRolloutRate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Field.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/FieldType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/FileLocation.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/FirehoseAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetCardinalityRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetCardinalityResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetEffectivePoliciesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetEffectivePoliciesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetIndexingConfigurationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetIndexingConfigurationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetJobDocumentRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetJobDocumentResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetLoggingOptionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetLoggingOptionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetOTAUpdateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetOTAUpdateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetPercentilesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetPercentilesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetPolicyRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetPolicyResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetPolicyVersionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetPolicyVersionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetRegistrationCodeRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetRegistrationCodeResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetStatisticsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetStatisticsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetTopicRuleDestinationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetTopicRuleDestinationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetTopicRuleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetTopicRuleResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetV2LoggingOptionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GetV2LoggingOptionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/GroupNameAndArn.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/HttpAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/HttpActionHeader.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/HttpAuthorization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/HttpContext.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/HttpUrlDestinationConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/HttpUrlDestinationProperties.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/HttpUrlDestinationSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ImplicitDeny.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/IndexStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/IotAnalyticsAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/IotEventsAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/IotSiteWiseAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Job.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/JobExecution.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/JobExecutionFailureType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/JobExecutionStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/JobExecutionStatusDetails.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/JobExecutionSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/JobExecutionSummaryForJob.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/JobExecutionSummaryForThing.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/JobExecutionsRolloutConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/JobProcessDetails.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/JobStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/JobSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/KeyPair.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/KinesisAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/LambdaAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListActiveViolationsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListActiveViolationsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAttachedPoliciesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAttachedPoliciesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuditFindingsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuditFindingsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuditMitigationActionsExecutionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuditMitigationActionsExecutionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuditMitigationActionsTasksRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuditMitigationActionsTasksResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuditSuppressionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuditSuppressionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuditTasksRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuditTasksResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuthorizersRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListAuthorizersResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListBillingGroupsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListBillingGroupsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListCACertificatesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListCACertificatesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListCertificatesByCARequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListCertificatesByCAResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListCertificatesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListCertificatesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListDimensionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListDimensionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListDomainConfigurationsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListDomainConfigurationsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListIndicesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListIndicesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListJobExecutionsForJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListJobExecutionsForJobResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListJobExecutionsForThingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListJobExecutionsForThingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListJobsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListJobsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListMitigationActionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListMitigationActionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListOTAUpdatesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListOTAUpdatesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListOutgoingCertificatesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListOutgoingCertificatesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListPoliciesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListPoliciesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListPolicyVersionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListPolicyVersionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListPrincipalThingsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListPrincipalThingsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListProvisioningTemplateVersionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListProvisioningTemplateVersionsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListProvisioningTemplatesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListProvisioningTemplatesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListRoleAliasesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListRoleAliasesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListScheduledAuditsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListScheduledAuditsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListSecurityProfilesForTargetRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListSecurityProfilesForTargetResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListSecurityProfilesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListSecurityProfilesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListStreamsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListStreamsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListTagsForResourceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListTagsForResourceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListTargetsForPolicyRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListTargetsForPolicyResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListTargetsForSecurityProfileRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListTargetsForSecurityProfileResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingGroupsForThingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingGroupsForThingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingGroupsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingGroupsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingPrincipalsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingPrincipalsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingRegistrationTaskReportsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingRegistrationTaskReportsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingRegistrationTasksRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingRegistrationTasksResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingTypesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingTypesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingsInBillingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingsInBillingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingsInThingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingsInThingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListThingsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListTopicRuleDestinationsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListTopicRuleDestinationsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListTopicRulesRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListTopicRulesResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListV2LoggingLevelsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListV2LoggingLevelsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListViolationEventsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ListViolationEventsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/LogLevel.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/LogTarget.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/LogTargetConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/LogTargetType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/LoggingOptionsPayload.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/MessageFormat.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/MetricDimension.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/MetricToRetain.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/MetricValue.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/MitigationAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/MitigationActionIdentifier.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/MitigationActionParams.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/MitigationActionType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/MqttContext.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/NonCompliantResource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/OTAUpdateFile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/OTAUpdateInfo.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/OTAUpdateStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/OTAUpdateSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/OutgoingCertificate.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/PercentPair.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Policy.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/PolicyTemplateName.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/PolicyVersion.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/PolicyVersionIdentifier.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/PresignedUrlConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Protocol.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ProvisioningHook.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ProvisioningTemplateSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ProvisioningTemplateVersionSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/PublishFindingToSnsParams.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/PutAssetPropertyValueEntry.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/PutItemInput.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RateIncreaseCriteria.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RegisterCACertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RegisterCACertificateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RegisterCertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RegisterCertificateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RegisterCertificateWithoutCARequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RegisterCertificateWithoutCAResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RegisterThingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RegisterThingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RegistrationConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RejectCertificateTransferRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RelatedResource.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RemoveThingFromBillingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RemoveThingFromBillingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RemoveThingFromThingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RemoveThingFromThingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ReplaceDefaultPolicyVersionParams.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ReplaceTopicRuleRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ReportType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RepublishAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ResourceAlreadyExistsException.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ResourceIdentifier.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ResourceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/RoleAliasDescription.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/S3Action.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/S3Destination.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/S3Location.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SalesforceAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ScheduledAuditMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SearchIndexRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SearchIndexResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SecurityProfileIdentifier.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SecurityProfileTarget.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SecurityProfileTargetMapping.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ServerCertificateStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ServerCertificateSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ServiceType.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SetDefaultAuthorizerRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SetDefaultAuthorizerResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SetDefaultPolicyVersionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SetLoggingOptionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SetV2LoggingLevelRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SetV2LoggingOptionsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SigV4Authorization.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SigningProfileParameter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SnsAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/SqsAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StartAuditMitigationActionsTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StartAuditMitigationActionsTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StartOnDemandAuditTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StartOnDemandAuditTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StartSigningJobParameter.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StartThingRegistrationTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StartThingRegistrationTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StatisticalThreshold.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Statistics.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Status.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StepFunctionsAction.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StopThingRegistrationTaskRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StopThingRegistrationTaskResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Stream.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StreamFile.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StreamInfo.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/StreamSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/Tag.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TagResourceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TagResourceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TargetSelection.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TaskStatistics.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TaskStatisticsForAuditCheck.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TestAuthorizationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TestAuthorizationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TestInvokeAuthorizerRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TestInvokeAuthorizerResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingAttribute.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingConnectivity.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingConnectivityIndexingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingDocument.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingGroupDocument.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingGroupIndexingConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingGroupIndexingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingGroupMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingGroupProperties.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingIndexingConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingIndexingMode.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingTypeDefinition.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingTypeMetadata.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ThingTypeProperties.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TimeoutConfig.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TlsContext.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TopicRule.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TopicRuleDestination.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TopicRuleDestinationConfiguration.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TopicRuleDestinationStatus.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TopicRuleDestinationSummary.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TopicRuleListItem.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TopicRulePayload.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TransferCertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TransferCertificateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/TransferData.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UntagResourceRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UntagResourceResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateAccountAuditConfigurationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateAccountAuditConfigurationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateAuditSuppressionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateAuditSuppressionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateAuthorizerRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateAuthorizerResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateBillingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateBillingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateCACertificateParams.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateCACertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateCertificateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateDeviceCertificateParams.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateDimensionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateDimensionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateDomainConfigurationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateDomainConfigurationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateDynamicThingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateDynamicThingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateEventConfigurationsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateEventConfigurationsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateIndexingConfigurationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateIndexingConfigurationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateJobRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateMitigationActionRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateMitigationActionResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateProvisioningTemplateRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateProvisioningTemplateResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateRoleAliasRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateRoleAliasResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateScheduledAuditRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateScheduledAuditResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateSecurityProfileRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateSecurityProfileResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateStreamRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateStreamResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateThingGroupRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateThingGroupResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateThingGroupsForThingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateThingGroupsForThingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateThingRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateThingResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateTopicRuleDestinationRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/UpdateTopicRuleDestinationResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ValidateSecurityProfileBehaviorsRequest.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ValidateSecurityProfileBehaviorsResult.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ValidationError.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ViolationEvent.h"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/include/aws/iot/model/ViolationEventType.h"
    )
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xUnspecifiedx" OR NOT CMAKE_INSTALL_COMPONENT)
  if(EXISTS "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-iot/aws-cpp-sdk-iot-targets.cmake")
    file(DIFFERENT EXPORT_FILE_CHANGED FILES
         "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-iot/aws-cpp-sdk-iot-targets.cmake"
         "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-iot/aws-cpp-sdk-iot-targets.cmake")
    if(EXPORT_FILE_CHANGED)
      file(GLOB OLD_CONFIG_FILES "$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-iot/aws-cpp-sdk-iot-targets-*.cmake")
      if(OLD_CONFIG_FILES)
        message(STATUS "Old export file \"$ENV{DESTDIR}${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-iot/aws-cpp-sdk-iot-targets.cmake\" will be replaced.  Removing files [${OLD_CONFIG_FILES}].")
        file(REMOVE ${OLD_CONFIG_FILES})
      endif()
    endif()
  endif()
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-iot" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-iot/aws-cpp-sdk-iot-targets.cmake")
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-iot" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-iot/aws-cpp-sdk-iot-targets-debug.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Dd][Ee][Bb][Uu][Gg][Oo][Pp][Tt])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-iot" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-iot/aws-cpp-sdk-iot-targets-debugopt.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-iot" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-iot/aws-cpp-sdk-iot-targets-minsizerel.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-iot" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-iot/aws-cpp-sdk-iot-targets-relwithdebinfo.cmake")
  endif()
  if("${CMAKE_INSTALL_CONFIG_NAME}" MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
    file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-iot" TYPE FILE FILES "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/CMakeFiles/Export/lib/cmake/aws-cpp-sdk-iot/aws-cpp-sdk-iot-targets-release.cmake")
  endif()
endif()

if("x${CMAKE_INSTALL_COMPONENT}x" STREQUAL "xDevelx" OR NOT CMAKE_INSTALL_COMPONENT)
  file(INSTALL DESTINATION "${CMAKE_INSTALL_PREFIX}/lib/cmake/aws-cpp-sdk-iot" TYPE FILE FILES
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/aws-cpp-sdk-iot-config.cmake"
    "C:/Users/isaac/Projects/aws-sdk-cpp/aws-cpp-sdk-iot/aws-cpp-sdk-iot-config-version.cmake"
    )
endif()

